spring:
  profiles:
    active: dev
    
---
spring:
  profiles: dev #开发环境
  application:
    name: springcloud-config-dev
name: Tom
age: 24
      
---
spring:
  profiles: test #测试环境
  application:
    name: springcloud-config-test
name: Jack
age: 16
